export const currencies = [
    { label: "US Dollar ($)", value: "USD", symbol: "$" },
    { label: "Euro (€)", value: "EUR", symbol: "€" },
    { label: "British Pound (£)", value: "GBP", symbol: "£" },
    { label: "Japanese Yen (¥)", value: "JPY", symbol: "¥" },
    { label: "Canadian Dollar ($)", value: "CAD", symbol: "$" },
    { label: "Australian Dollar ($)", value: "AUD", symbol: "$" },
    { label: "Swiss Franc (Fr)", value: "CHF", symbol: "Fr" },
    { label: "Chinese Yuan (¥)", value: "CNY", symbol: "¥" },
    { label: "Indian Rupee (₹)", value: "INR", symbol: "₹" },
    { label: "Brazilian Real (R$)", value: "BRL", symbol: "R$" },
    { label: "Russian Ruble (₽)", value: "RUB", symbol: "₽" },
    { label: "South Korean Won (₩)", value: "KRW", symbol: "₩" },
    { label: "Mexican Peso ($)", value: "MXN", symbol: "$" },
    { label: "Singapore Dollar ($)", value: "SGD", symbol: "$" },
    { label: "New Zealand Dollar ($)", value: "NZD", symbol: "$" },
    { label: "Hong Kong Dollar ($)", value: "HKD", symbol: "$" },
    { label: "Swedish Krona (kr)", value: "SEK", symbol: "kr" },
    { label: "Norwegian Krone (kr)", value: "NOK", symbol: "kr" },
    { label: "Danish Krone (kr)", value: "DKK", symbol: "kr" },
    { label: "Turkish Lira (₺)", value: "TRY", symbol: "₺" },
] as const
